version: '3.8'
services:
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:8.2-apache
    platform: linux/amd64
    ports:
      - 8080:80
    volumes:
      - ./src/public/:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/
